::curl https://sookocheff.com/fonts/lora/lora-v12-latin-regular.eot -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-regular.woff2 -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-regular.woff -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-regular.ttf -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-regular.svg -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-700.eot -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-700.woff2 -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-700.woff -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-700.ttf -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-700.svg -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-italic.eot -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-italic.woff2 -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-italic.woff -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-italic.ttf -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-italic.svg -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-700italic.eot -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-700italic.woff2 -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-700italic.woff -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-700italic.ttf -O
curl https://sookocheff.com/fonts/lora/lora-v12-latin-700italic.svg -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-300.eot -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-300.woff2 -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-300.woff -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-300.ttf -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-300.svg -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-300italic.eot -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-300italic.woff2 -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-300italic.woff -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-300italic.ttf -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-300italic.svg -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-regular.eot -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-regular.woff2 -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-regular.woff -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-regular.ttf -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-regular.svg -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-italic.eot -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-italic.woff2 -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-italic.woff -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-italic.ttf -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-italic.svg -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-600.eot -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-600.woff2 -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-600.woff -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-600.ttf -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-600.svg -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-600italic.eot -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-600italic.woff2 -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-600italic.woff -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-600italic.ttf -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-600italic.svg -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-700.eot -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-700.woff2 -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-700.woff -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-700.ttf -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-700.svg -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-800.eot -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-800.woff2 -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-800.woff -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-800.ttf -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-800.svg -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-700italic.eot -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-700italic.woff2 -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-700italic.woff -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-700italic.ttf -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-700italic.svg -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-800italic.eot -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-800italic.woff2 -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-800italic.woff -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-800italic.ttf -O
curl https://sookocheff.com/fonts/open-sans/open-sans-v15-latin-800italic.svg -O
curl } -O